---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен иметь возможность "Регистрации" и "Авторизации" пользователя
  - Сайт нужно адаптировать для просмотра с различных устройствах
  - Пользователь должен иметь возможность оформления заказа 
  - В корзине отсутствует кнопка изменения количества добавленых товаров
  - При оформлении заказа у товара с длинным названием колличество товара смещается к цене товара
  - При оформлении заказа кнопка "Close" в виде крестика не работает
  - В каталоге товаров фото не должно растягиваться
  - На странице товара нет возможности открыть в модальном окне фото и пролистать если их несколько
  - При смене языка в меню панели меняется язык только в инструментах Интернет магазина
  - При смене языков не отображается иконка Английского языка
  - Стиль кнопки "добавить в корзину"должен быть один
