---
functional:
  - Требование 3
  - Требование 4
  - Требование 5
  - Требование 8
  - Требование 9
non-functional:
  - Требование 1
  - Требование 2
  - Требование 6
  - Требование 7
  - Требование 10
implicit:
  - Нет кнопки "Регистрация" "Авторизация"
  - Сайт нужно адаптировать для просмотра с различных устройствах
  - В каталоге товаров не выводится рейтинг товара
  - При добавлении товара в корзину нет возможности выбрать количество
  - При добавлении нескольких товаров в корзину , и редактировании корзины сумма заказа не уменьшается
  - В корзине отсутствует кнопка изменения количества добавленых товаров
  - При оформлении заказа выводится не корректная сумма заказа
  - При оформлении заказа кнопка "Close" в виде крестика не работает
  - В каталоге товаров картинка не должна растягиваться
  - На странице товара нет возможности открыть в модальном окне картинку и пролистать если их несколько
  - При смене языка в меню панели меняется язык только в инструментах Интернет магазина
  - Стиль кнопки "добавить в корзину"должен быть один
